# Generated by Django 3.2.5 on 2021-08-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=250)),
                ('image1', models.ImageField(upload_to='images/')),
                ('title2', models.CharField(blank=True, max_length=250)),
                ('image2', models.ImageField(blank=True, upload_to='images/')),
                ('title3', models.CharField(blank=True, max_length=250)),
                ('image3', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
