# Generated by Django 3.2.5 on 2021-08-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Скидка'),
            preserve_default=False,
        ),
    ]
